package com.secureinsure.admin.service;

import com.secureinsure.admin.dto.SystemAuditDto;
import com.secureinsure.admin.dto.SystemConfigurationDto;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

public interface AdminService {

    // System Audit Operations
    SystemAuditDto createAudit(SystemAuditDto auditDto);
    SystemAuditDto getAuditById(Long id);
    SystemAuditDto getAuditByAuditId(String auditId);
    Page<SystemAuditDto> getAllAudits(Pageable pageable);
    SystemAuditDto updateAudit(Long id, SystemAuditDto auditDto);
    void deleteAudit(Long id);
    List<SystemAuditDto> getAuditsByUserId(Long userId);
    List<SystemAuditDto> getAuditsByUsername(String username);
    List<SystemAuditDto> getAuditsByAction(String action);
    List<SystemAuditDto> getAuditsByEntityType(String entityType);
    List<SystemAuditDto> getAuditsByEntityId(Long entityId);
    List<SystemAuditDto> getAuditsBySuccess(Boolean success);
    List<SystemAuditDto> getSuccessfulAudits();
    List<SystemAuditDto> getFailedAudits();
    List<SystemAuditDto> getAuditsByIpAddress(String ipAddress);
    List<SystemAuditDto> getAuditsBySessionId(String sessionId);
    List<SystemAuditDto> getAuditsByDateRange(LocalDateTime startDate, LocalDateTime endDate);
    List<SystemAuditDto> getAuditsByUserIdAndDateRange(Long userId, LocalDateTime startDate, LocalDateTime endDate);
    List<SystemAuditDto> getAuditsByActionAndDateRange(String action, LocalDateTime startDate, LocalDateTime endDate);
    List<SystemAuditDto> getAuditsByEntityTypeAndDateRange(String entityType, LocalDateTime startDate, LocalDateTime endDate);
    List<SystemAuditDto> getAuditsBySuccessAndDateRange(Boolean success, LocalDateTime startDate, LocalDateTime endDate);
    List<SystemAuditDto> getAuditsByIpAddressAndDateRange(String ipAddress, LocalDateTime startDate, LocalDateTime endDate);
    Page<SystemAuditDto> getAuditsByUserId(Long userId, Pageable pageable);
    Page<SystemAuditDto> getAuditsByUsername(String username, Pageable pageable);
    Page<SystemAuditDto> getAuditsByAction(String action, Pageable pageable);
    Page<SystemAuditDto> getAuditsByEntityType(String entityType, Pageable pageable);
    Page<SystemAuditDto> getAuditsBySuccess(Boolean success, Pageable pageable);
    Page<SystemAuditDto> getAuditsByIpAddress(String ipAddress, Pageable pageable);
    Page<SystemAuditDto> getAuditsByDateRange(LocalDateTime startDate, LocalDateTime endDate, Pageable pageable);
    Page<SystemAuditDto> searchAudits(SystemAuditDto searchCriteria, Pageable pageable);
    Page<SystemAuditDto> searchAudits(String query, Pageable pageable);

    // System Configuration Operations
    SystemConfigurationDto createConfiguration(SystemConfigurationDto configDto);
    SystemConfigurationDto getConfigurationById(Long id);
    SystemConfigurationDto getConfigurationByKey(String configKey);
    Page<SystemConfigurationDto> getAllConfigurations(Pageable pageable);
    SystemConfigurationDto updateConfiguration(Long id, SystemConfigurationDto configDto);
    SystemConfigurationDto updateConfiguration(String configKey, SystemConfigurationDto configDto);
    void deleteConfiguration(Long id);
    void deleteConfiguration(String configKey);
    List<SystemConfigurationDto> getConfigurationsByCategory(String category);
    List<SystemConfigurationDto> getConfigurationsByConfigType(String configType);
    List<SystemConfigurationDto> getConfigurationsByEnvironment(String environment);
    List<SystemConfigurationDto> getConfigurationsByIsEncrypted(Boolean isEncrypted);
    List<SystemConfigurationDto> getConfigurationsByIsSensitive(Boolean isSensitive);
    List<SystemConfigurationDto> getConfigurationsByIsReadonly(Boolean isReadonly);
    List<SystemConfigurationDto> getConfigurationsByVersion(String version);
    List<SystemConfigurationDto> getConfigurationsByCreatedBy(Long createdBy);
    List<SystemConfigurationDto> getConfigurationsByUpdatedBy(Long updatedBy);
    List<SystemConfigurationDto> getConfigurationsByDateRange(LocalDateTime startDate, LocalDateTime endDate);
    List<SystemConfigurationDto> getConfigurationsByUpdatedDateRange(LocalDateTime startDate, LocalDateTime endDate);
    Page<SystemConfigurationDto> getConfigurationsByCategory(String category, Pageable pageable);
    Page<SystemConfigurationDto> getConfigurationsByConfigType(String configType, Pageable pageable);
    Page<SystemConfigurationDto> getConfigurationsByEnvironment(String environment, Pageable pageable);
    Page<SystemConfigurationDto> getConfigurationsByIsEncrypted(Boolean isEncrypted, Pageable pageable);
    Page<SystemConfigurationDto> getConfigurationsByIsSensitive(Boolean isSensitive, Pageable pageable);
    Page<SystemConfigurationDto> getConfigurationsByIsReadonly(Boolean isReadonly, Pageable pageable);
    Page<SystemConfigurationDto> searchConfigurations(SystemConfigurationDto searchCriteria, Pageable pageable);
    List<SystemConfigurationDto> getConfigurationsByKeys(List<String> configKeys);
    List<SystemConfigurationDto> getSensitiveConfigurations();
    List<SystemConfigurationDto> getEncryptedConfigurations();
    List<SystemConfigurationDto> getReadonlyConfigurations();
    List<SystemConfigurationDto> getConfigurationsWithValidation();
    List<SystemConfigurationDto> getRecentlyUpdatedConfigurations(LocalDateTime since);
    void updateConfigValue(String configKey, String newValue);
    void updateReadonlyStatus(String configKey, Boolean readonly);
    void updateSensitiveStatus(String configKey, Boolean sensitive);

    // System Management Operations
    Map<String, Object> getSystemStatistics();
    Map<String, Object> getAuditStatistics();
    Map<String, Object> getConfigurationStatistics();
    Map<String, Object> getPerformanceMetrics();
    Map<String, Object> getSecurityMetrics();
    Map<String, Object> getSystemHealth();
    Map<String, Object> getSystemMetrics();
    Map<String, Object> getTopActions();
    Map<String, Object> getTopEntityTypes();
    Map<String, Object> getTopUsers();
    Map<String, Object> getTopIpAddresses();
    Map<String, Object> getTopErrors();
    Map<String, Object> getConfigurationCountByCategory();
    Map<String, Object> getConfigurationCountByType();
    Map<String, Object> getConfigurationCountByEnvironment();
    Map<String, Object> getConfigurationCountByVersion();
    Double getAverageExecutionTime();
    Double getAverageExecutionTimeByAction(String action);
    Long getMaxExecutionTime();
    Long getMinExecutionTime();
    Long getSuccessfulAuditsCount();
    Long getFailedAuditsCount();
    Long getAuditsCountByAction(String action);
    Long getAuditsCountByEntityType(String entityType);
    Long getAuditsCountByUserId(Long userId);
    Long getAuditsCountByIpAddress(String ipAddress);
    Long getAuditsCountByDateRange(LocalDateTime startDate, LocalDateTime endDate);
    Long getAuditsCountByUserIdAndDateRange(Long userId, LocalDateTime startDate, LocalDateTime endDate);
    Long getAuditsCountByActionAndDateRange(String action, LocalDateTime startDate, LocalDateTime endDate);
    Long getEncryptedConfigurationsCount();
    Long getSensitiveConfigurationsCount();
    Long getReadonlyConfigurationsCount();
    Long getConfigurationsCountByCategory(String category);
    Long getConfigurationsCountByConfigType(String configType);
    Long getConfigurationsCountByEnvironment(String environment);
    Long getConfigurationsCountByVersion(String version);
    Long getConfigurationsCountByCreatedBy(Long createdBy);
    Long getConfigurationsCountByUpdatedBy(Long updatedBy);

    // Maintenance Operations
    void cleanupOldAudits(LocalDateTime cutoffDate);
    void cleanupOldConfigurations(LocalDateTime cutoffDate);
    Long countAuditsOlderThan(LocalDateTime cutoffDate);
    Long countConfigurationsOlderThan(LocalDateTime cutoffDate);
    void backupSystemData();
    void restoreSystemData(String backupId);
    void performSystemMaintenance();
    void runSystemHealthCheck();
    void generateSystemReport();
    void exportAuditData(LocalDateTime startDate, LocalDateTime endDate);
    void exportConfigurationData();
    void importConfigurationData(String configData);
    void optimizeSystemPerformance();
    void updateSystemSettings(Map<String, String> settings);
    void reloadSystemConfiguration();
    void restartSystemServices();
    void shutdownSystem();
    void emergencyShutdown();
    void emergencyRestart();

    // Validation Operations
    boolean validateAudit(SystemAuditDto auditDto);
    boolean validateConfiguration(SystemConfigurationDto configDto);
    boolean validateSystemHealth();
    boolean validateSystemSecurity();
    boolean validateSystemPerformance();
    boolean validateSystemIntegrity();
    boolean validateSystemConfiguration();
    boolean validateSystemBackup();
    boolean validateSystemRestore(String backupId);
    boolean validateSystemMaintenance();
    boolean validateSystemReport();
    boolean validateSystemExport();
    boolean validateSystemImport(String importData);
    boolean validateSystemUpdate();
    boolean validateSystemRestart();
    boolean validateSystemShutdown();

    // Utility Operations
    String generateAuditId();
    String generateRandomString(int length);
    String generateBackupId();
    String generateMaintenanceId();
    String generateReportId();
    String generateExportId();
    String generateImportId();
    String generateUpdateId();
    String generateRestartId();
    String generateShutdownId();
    String generateEmergencyId();
    String formatExecutionTime(Long executionTimeMs);
    String formatTimestamp(LocalDateTime timestamp);
    String getAuditSummary(SystemAuditDto auditDto);
    String getConfigurationSummary(SystemConfigurationDto configDto);
    String getSystemSummary();
    String getAuditSummary();
    String getConfigurationSummary();
    String getPerformanceSummary();
    String getSecuritySummary();
    String getHealthSummary();
    String getMetricsSummary();
    String getActionsSummary();
    String getEntityTypesSummary();
    String getUsersSummary();
    String getIpAddressesSummary();
    String getErrorsSummary();
    String getCategoriesSummary();
    String getTypesSummary();
    String getEnvironmentsSummary();
    String getVersionsSummary();
    String getExecutionTimeSummary();
    String getSuccessSummary();
    String getFailureSummary();
    String getEncryptedSummary();
    String getSensitiveSummary();
    String getReadonlySummary();
    String getModifiableSummary();
    String getDisplaySummary();
    String getValidationSummary();
    String getAllowedValuesSummary();
    String getNumericSummary();
    String getBooleanSummary();
    String getStringSummary();
    String getJsonSummary();
    String getConfigSummary();
    String getValidValueSummary();
    String getInAllowedValuesSummary();

    // Health Check Operations
    void healthCheck();
    boolean isSystemHealthy();
    boolean isSystemSecure();
    boolean isSystemPerformant();
    boolean isSystemIntegrityValid();
    boolean isSystemConfigurationValid();
    boolean isSystemBackupValid();
    boolean isSystemRestoreValid(String backupId);
    boolean isSystemMaintenanceValid();
    boolean isSystemReportValid();
    boolean isSystemExportValid();
    boolean isSystemImportValid(String importData);
    boolean isSystemUpdateValid();
    boolean isSystemRestartValid();
    boolean isSystemShutdownValid();
    boolean isEmergencyShutdownValid();
    boolean isEmergencyRestartValid();
} 