import { test, expect, Page } from '@playwright/test';
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

interface TestError {
  testName: string;
  error: string;
  screenshot?: string;
  trace?: string;
  timestamp: string;
}

interface SelfHealingConfig {
  maxRetries: number;
  autoFix: boolean;
  generatePrompts: boolean;
  outputDir: string;
}

export class SelfHealingRunner {
  private config: SelfHealingConfig;
  private errors: TestError[] = [];

  constructor(config: Partial<SelfHealingConfig> = {}) {
    this.config = {
      maxRetries: 3,
      autoFix: true,
      generatePrompts: true,
      outputDir: './self-heal',
      ...config
    };
  }

  async runTest(testName: string, testFn: (page: Page) => Promise<void>) {
    let retries = 0;
    let lastError: string = '';

    while (retries < this.config.maxRetries) {
      try {
        await test(testName, async ({ page }) => {
          await testFn(page);
        });
        console.log(`✅ ${testName} passed on attempt ${retries + 1}`);
        return true;
      } catch (error: any) {
        lastError = error.message;
        retries++;
        
        console.log(`❌ ${testName} failed on attempt ${retries}: ${lastError}`);
        
        // Capture error details
        const errorDetails: TestError = {
          testName,
          error: lastError,
          timestamp: new Date().toISOString()
        };

        this.errors.push(errorDetails);

        if (retries < this.config.maxRetries) {
          console.log(`🔄 Retrying ${testName} (${retries}/${this.config.maxRetries})...`);
          
          if (this.config.autoFix) {
            await this.attemptAutoFix(errorDetails);
          }
          
          // Wait before retry
          await new Promise(resolve => setTimeout(resolve, 2000));
        }
      }
    }

    console.log(`💥 ${testName} failed after ${this.config.maxRetries} attempts`);
    
    if (this.config.generatePrompts) {
      await this.generateHealingPrompt(testName, lastError);
    }

    return false;
  }

  private async attemptAutoFix(error: TestError) {
    console.log(`🔧 Attempting auto-fix for ${error.testName}...`);
    
    // Common auto-fix patterns
    if (error.error.includes('element was detached from the DOM')) {
      console.log('🔧 Detected DOM detachment - adding wait strategies...');
      // This would be implemented in the actual test
    }
    
    if (error.error.includes('timeout')) {
      console.log('🔧 Detected timeout - increasing wait times...');
      // This would be implemented in the actual test
    }
    
    if (error.error.includes('not found')) {
      console.log('🔧 Detected element not found - trying alternative selectors...');
      // This would be implemented in the actual test
    }
  }

  private async generateHealingPrompt(testName: string, error: string) {
    const promptDir = path.join(this.config.outputDir, 'prompts');
    if (!fs.existsSync(promptDir)) {
      fs.mkdirSync(promptDir, { recursive: true });
    }

    const promptContent = `# Self-Healing Prompt for ${testName}

## Error Details
- **Test**: ${testName}
- **Error**: ${error}
- **Timestamp**: ${new Date().toISOString()}

## Suggested Fixes

### 1. Element Not Found
If the error mentions "not found" or "timeout":
\`\`\`typescript
// Add more robust selectors
const element = await page.locator('selector').first();
await expect(element).toBeVisible({ timeout: 10000 });
\`\`\`

### 2. DOM Detachment
If the error mentions "detached from the DOM":
\`\`\`typescript
// Add wait for stability
await page.waitForLoadState('networkidle');
await page.waitForSelector('selector', { state: 'attached' });
\`\`\`

### 3. Timing Issues
If the error mentions "timeout":
\`\`\`typescript
// Increase timeouts
await expect(element).toBeVisible({ timeout: 30000 });
await page.waitForTimeout(1000);
\`\`\`

### 4. Network Issues
If the error mentions network or API:
\`\`\`typescript
// Wait for network requests
await page.waitForResponse(response => response.url().includes('/api/'));
\`\`\`

## Auto-Generated Fix Command
\`\`\`bash
npm run e2e:fix -- --test="${testName}"
\`\`\`

## Manual Fix Steps
1. Check if the application is running on the correct port
2. Verify all required services are started
3. Check for JavaScript errors in the browser console
4. Ensure all dependencies are installed
5. Verify the test selectors are correct

## Generated by Self-Healing Runner
${new Date().toISOString()}
`;

    const fileName = `${testName.replace(/[^a-zA-Z0-9]/g, '-')}-${Date.now()}.md`;
    const filePath = path.join(promptDir, fileName);
    
    fs.writeFileSync(filePath, promptContent);
    console.log(`📝 Generated healing prompt: ${filePath}`);
  }

  async generateReport() {
    const reportDir = path.join(this.config.outputDir, 'reports');
    if (!fs.existsSync(reportDir)) {
      fs.mkdirSync(reportDir, { recursive: true });
    }

    const reportContent = `# Self-Healing Test Report

## Summary
- **Total Tests**: ${this.errors.length}
- **Failed Tests**: ${this.errors.length}
- **Success Rate**: ${this.errors.length === 0 ? '100%' : '0%'}

## Failed Tests
${this.errors.map(error => `
### ${error.testName}
- **Error**: ${error.error}
- **Timestamp**: ${error.timestamp}
`).join('\n')}

## Recommendations
1. Review the generated healing prompts in the prompts/ directory
2. Implement the suggested fixes
3. Re-run the tests with: \`npm run e2e\`
4. Consider increasing timeout values for flaky tests

## Generated by Self-Healing Runner
${new Date().toISOString()}
`;

    const reportPath = path.join(reportDir, `report-${Date.now()}.md`);
    fs.writeFileSync(reportPath, reportContent);
    console.log(`📊 Generated test report: ${reportPath}`);
  }
}

// Export for use in tests
export { SelfHealingRunner };
